name: docker image update

on:
  workflow_run:
    workflows: [Build]
    branches: [master]
    types: [completed]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-2022]
        include:
        - os: ubuntu-latest
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          file: linux.Dockerfile
          tags: biosmarcel/scribble.rs:latest

        - os: windows-2022
          platforms: windows/amd64
          file: windows.Dockerfile
          tags: biosmarcel/scribble.rs:windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: ${{ !contains(matrix.os, 'windows') }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: ${{ matrix.platforms }}
          push: true
          tags:  ${{ matrix.tags }}

